// Generated by GitHub Copilot

const currencyInputs = [
  'vehicle',
  'costPerCrew',
  'foodPerCrew',
  'packing',
  'toll',
  'other'
]

function formatNumber(value) {
  return new Intl.NumberFormat('id-ID').format(value)
}

function formatRupiah(value) {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    maximumFractionDigits: 0
  }).format(value)
}

function parseInputValue(value) {
  return Number(
    value
      .replace(/\./g, '')
      .replace(/,/g, '')
  ) || 0
}

function attachThousandsSeparator() {
  currencyInputs.forEach((id) => {
    const input = document.getElementById(id)

    input.addEventListener('input', (e) => {
      const rawValue = e.target.value.replace(/\D/g, '')

      if (!rawValue) {
        e.target.value = ''
        return
      }

      e.target.value = formatNumber(Number(rawValue))
    })
  })
}

function getMargin(adjustedCost) {
  if (adjustedCost < 1_000_000) return 0.70
  if (adjustedCost < 3_000_000) return 0.50
  if (adjustedCost < 7_000_000) return 0.35
  if (adjustedCost < 15_000_000) return 0.25
  return 0.20
}

function getMinimumProfit(adjustedCost) {
  if (adjustedCost < 1_000_000) return 500_000
  if (adjustedCost < 3_000_000) return 1_000_000
  if (adjustedCost < 7_000_000) return 1_500_000
  if (adjustedCost < 15_000_000) return 2_500_000
  return 4_000_000
}

function calculate() {
  const vehicle = parseInputValue(document.getElementById('vehicle').value)
  const crewCount = Number(document.getElementById('crewCount').value) || 0
  const costPerCrew = parseInputValue(document.getElementById('costPerCrew').value)
  const foodPerCrew = parseInputValue(document.getElementById('foodPerCrew').value)
  const packing = parseInputValue(document.getElementById('packing').value)
  const toll = parseInputValue(document.getElementById('toll').value)
  const other = parseInputValue(document.getElementById('other').value)
  const negotiationBuffer = Number(document.getElementById('customerType').value)

  // Crew calculations
  const manpower = crewCount * costPerCrew
  const food = crewCount * foodPerCrew

  // Total job cost
  const jobCost = vehicle + manpower + food + packing + toll + other

  // Operational buffer
  const operationalBuffer = jobCost * 0.10
  const adjustedCost = jobCost + operationalBuffer

  // Margin calculation
  const margin = getMargin(adjustedCost)
  const marginProfit = adjustedCost * margin

  // Minimum profit floor
  const minimumProfit = getMinimumProfit(adjustedCost)

  // Final profit
  const finalProfit = Math.max(marginProfit, minimumProfit)

  // Internal target
  const internalTargetPrice = adjustedCost + finalProfit

  // Final offer
  const initialOfferPrice = internalTargetPrice * (1 + negotiationBuffer)

  // Render result
  document.getElementById('result').style.display = 'block'
  document.getElementById('manpowerResult').innerText = formatRupiah(manpower)
  document.getElementById('foodResult').innerText = formatRupiah(food)
  document.getElementById('jobCostResult').innerText = formatRupiah(jobCost)
  document.getElementById('bufferResult').innerText = formatRupiah(operationalBuffer)
  document.getElementById('adjustedCostResult').innerText = formatRupiah(adjustedCost)
  document.getElementById('marginProfitResult').innerText = formatRupiah(marginProfit)
  document.getElementById('minProfitResult').innerText = formatRupiah(minimumProfit)
  document.getElementById('finalProfitResult').innerText = formatRupiah(finalProfit)
  document.getElementById('targetPriceResult').innerText = formatRupiah(internalTargetPrice)
  document.getElementById('negotiationResult').innerText = `${(negotiationBuffer * 100).toFixed(0)}%`
  document.getElementById('offerPriceResult').innerText = formatRupiah(initialOfferPrice)
}

attachThousandsSeparator()
document.getElementById('calculateBtn').addEventListener('click', calculate)
