// Generated by GitHub Copilot

let currentLang = 'en'

const translations = {
  en: {
    title: 'Margin Calculator',
    labelVehicle: 'Vehicle / Transport Cost',
    labelCrewCount: 'Crew Count',
    labelCostPerCrew: 'Cost per Crew',
    labelFoodPerCrew: 'Food per Crew',
    labelPacking: 'Material / Equipment',
    labelToll: 'Toll / Parking',
    labelOther: 'Other Expenses',
    labelOutOfTown: 'Out of Town',
    outOfTownYes: 'Destination outside city',
    labelMealsCount: 'Meals per Person',
    btnCalculate: 'Calculate Price',
    btnReset: 'Reset',
    resJobCost: 'Total Job Cost',
    resBuffer: 'Operational Buffer (10%)',
    resAdjusted: 'Adjusted Cost',
    resMargin: 'Margin Profit',
    resMinProfit: 'Minimum Profit Floor',
    resFinalProfit: 'Final Profit Used',
    resTarget: 'Internal Target Price',
    resOffer: 'Initial Offer Price'
  },
  id: {
    title: 'Kalkulator Margin',
    labelVehicle: 'Biaya Kendaraan / Transportasi',
    labelCrewCount: 'Jumlah Kru',
    labelCostPerCrew: 'Biaya per Kru',
    labelFoodPerCrew: 'Makan per Kru',
    labelPacking: 'Material / Peralatan',
    labelToll: 'Tol / Parkir',
    labelOther: 'Pengeluaran Lainnya',
    labelOutOfTown: 'Luar Kota',
    outOfTownYes: 'Tujuan di luar kota',
    labelMealsCount: 'Jumlah Makan per Orang',
    btnCalculate: 'Hitung Harga',
    btnReset: 'Reset',
    resJobCost: 'Total Biaya Pekerjaan',
    resBuffer: 'Buffer Operasional (10%)',
    resAdjusted: 'Biaya yang Disesuaikan',
    resMargin: 'Margin Keuntungan',
    resMinProfit: 'Batas Minimum Keuntungan',
    resFinalProfit: 'Keuntungan Akhir',
    resTarget: 'Harga Target Internal',
    resOffer: 'Harga Penawaran Awal'
  }
}

/**
 * Applies the selected language to all data-i18n elements.
 * @param {'en'|'id'} lang - Target language code
 */
function applyLang(lang) {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n')
    const text = translations[lang][key]
    if (text) el.textContent = text
  })
  document.documentElement.lang = lang
  const btn = document.getElementById('langToggle')
  btn.textContent = lang === 'en' ? 'ID' : 'EN'
  btn.setAttribute(
    'aria-label',
    lang === 'en' ? 'Switch language to Indonesian' : 'Switch language to English'
  )
  currentLang = lang
}

document
  .getElementById('langToggle')
  .addEventListener('click', () => {
    applyLang(currentLang === 'en' ? 'id' : 'en')
  })
